---
name: Newman Run2

on:
  workflow_dispatch: null

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: MycarСalсulate.postman_collection.json
          iterationData: Calculate.json
