name: Newman Run

on: workflow_dispatch   

jobs:
  newman:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: MycarСalсulate.postman_collection.json
          iterationData: Calculate.json
